# Day-5-of-Learning-Java
In the day 5 I have learn about the EXCEPTION HANDLING and made programs based on problems { Handling the exception using try-catch block, Handling a NullPointerException, Writing data to a text file using FileWriter, Defining a user-defined exception AgeNotValidException, Simulating a bank transaction  exception InsufficientFundsException }.

 The problems are as following:-
 
Q1. Write a java program that performs division of two numbers, where the denominator is zero, and handle the exception using try-catch to prevent program termination. Also,
    print a message after the exception handling block.
    
Q2. Demonstrate a Java program named ExcepTest3 that handles a NullPointerException using try-catch-finally blocks. In this program, initialize a String variable with null 
    and attempt to access its length inside the try block to deliberately cause the exception. Handle the exception in the catch block, and in the finally block, assign a 
    valid value to the String and print it.
    
Q3. Demonstrate a Java program named WriteData_Demo that writes data to a text file using FileWriter. In this program, create a file named file.txt and write some sample text to it inside the try block. Handle possible IOException using a catch block, and ensure the file writer resource is closed properly inside the finally block.

Q4. Demonstrate a Java program that defines a user-defined exception class AgeNotValidException to validate the age for voting. If age is less than 18, throw the exception.

Q5. Demonstrate a Java program with the class name BankDemo to simulate a bank transaction scenario. Define a user-defined exception class named InsufficientFundsException which is thrown when the withdrawal amount exceeds the account balance.
